import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '@/Compoments/UI/Banner/Banner'
import LatestProject from '@/Compoments/UI/LatestProject/LatestProject'
import Services from '@/Compoments/UI/Services/Services'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Luxury Living</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner></Banner>
        <LatestProject></LatestProject>
        <Services></Services>
      </main>
    </>
  )
}
